import { exec } from "node:child_process"
import { marked } from 'marked'
import * as path from "node:path"
import process from "node:process"
import * as fs from "node:fs";

export const generateHtml = (conclusion: string, TrainerResponse: string, SupportAgent: string) => {
    return `
    <!DOCTYPE html>
<html lang="th">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Activity Suggestion</title>
    <style>
        :root {
            --primary-color: #1a4e83;
            --background-light: #f9f9f9;
            --box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
            --border-radius: 12px;
        }

        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #fff;
            color: #333;
            max-width: 900px;
            margin: 0 auto;
            padding: 32px 24px;
            line-height: 1.8;
        }

        h1 {
            font-size: 2.5rem;
            color: var(--primary-color);
            margin-bottom: 24px;
            text-align: center;
        }

        h2 {
            color: var(--primary-color);
            margin-bottom: 16px;
            font-size: 1.5rem;
        }

        section {
            background-color: var(--background-light);
            border-radius: var(--border-radius);
            padding: 24px;
            margin-bottom: 28px;
            box-shadow: var(--box-shadow);
            transition: transform 0.2s ease;
        }

        section:hover {
            transform: translateY(-4px);
        }

        p, li {
            font-size: 1rem;
            margin-bottom: 1em;
        }

        li {
            padding-left: 1em;
            list-style: disc;
        }

        aside {
            background-color: #eaf1f8;
            border-left: 5px solid var(--primary-color);
            border-radius: var(--border-radius);
            padding: 16px 20px;
            margin-top: 36px;
            font-style: italic;
            box-shadow: var(--box-shadow);
        }

        code {
            background-color: #eee;
            padding: 2px 6px;
            border-radius: 4px;
        }
    </style>
</head>
<body>
    <h1>Activity Suggestion</h1>

    <section>
        <h2>Translator Information</h2>
        ${marked(TrainerResponse)}
    </section>

    <section>
        <h2>Support Agent</h2>
        ${marked(SupportAgent)}
    </section>

    <section>
        <h2>Conclusion</h2>
        ${marked(conclusion)}
    </section>

    <aside>
        <p>Generated by AI</p>
    </aside>
</body>
</html>

    `
}

export const buildHtmlFileAndOpen = (conclusion: string, TrainerResponse: string, SupportAgent: string) => {
    const html = generateHtml(conclusion, TrainerResponse, SupportAgent)
    const fileName = 'activity_suggestion.html'
    fs.writeFile(fileName, html, (err) => {
        if (err) {
            console.error(`Error writing file: ${err}`)
            return
        }
        console.log(`HTML file created: ${fileName}`)
        openInBrowser(fileName)
    })
}

export const openInBrowser = (fileName: string) => {
    const filePath = path.resolve(fileName)
    const command = process.platform === 'win32' ? 'start' : process.platform === 'darwin' ? 'open' : 'xdg-open'

    exec(`${command} ${filePath}`, (error) => {
        if (error) {
            console.error(`Error opening file: ${error}`)
        }
    })
}